### ISSUE TITLE
Cross Compile for RIO Target

### ISSUE THREAD

**Issue by coalman321** [Worthington-Robotics/2021ROS2Build#1]
We need to have a cross compiled binary form of ROS2 that can be deployed to the target as part of our standard deploy process.

Ideally the compilation should try to use as much static library usage as possible due to the constraints of the target and deploying linked libraries is a bit more complicated.

Currently the plan is to use the dockerfile contained in this repo to build ROS2 against the provided FRC toolchain. 
[Dockerfile](https://github.com/Worthington-Robotics/2021ROS2Build/blob/master/dashing_compile.dockerfile)

The current ROS2 target version to support for this season is the Foxy release.

**Comment by coalman321** [comment]
Current status report: 
Last build status failed, Looks to be having trouble building TinyXML properly. It complains about certain CMAKE config options not being set.  We may be able to compile this one statically and place it inside our sysroot similar to our handling of TinyXML2.
[Relevant GIST of output](https://gist.github.com/Spazzinq/e7cf247327e41bfbf48199804533030c) 

We are however able to compile POCO as expected.

**Comment by coalman321** [comment]
@emersonknapp This is the current status of our build process thus far. Let us know if you have any thoughts that might get us closer.

**Comment by Spazzinq** [comment]
Current Status Report:
Unable to finish build due to missing CMAKE package configuration files. Most posts online suggest that ROS2 is not sourced properly, or the workspace bash is not, but I have tried to source both to no avail.

[Error](https://gist.github.com/Spazzinq/19dfa657a51a538a772e7b273c981215)

[Relevant ROS Answers post](https://answers.ros.org/question/343933/how-can-i-build-navigation2-from-source/)
